name: emotion_app
description: Emotion_detection_project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  camera: ^0.11.1
  video_player: ^2.7.0
  cupertino_icons: ^1.0.2

  # WebView (full suite, cần để hoạt động đúng)
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.2
  webview_flutter_wkwebview: ^3.20.0
  webview_flutter_platform_interface: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

